import { Component, OnInit, ViewChild } from '@angular/core';
import { Chart } from 'chart.js';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';

@Component({
  selector: 'app-details',
  templateUrl: './details.component.html',
  styleUrls: ['./details.component.scss'],
})
export class DetailsComponent implements OnInit {
  chart: any;
  public ELEMENT_DATA: any[] = [
    {
      Country: 'United States',
      Company: 'Bayer',
      'Period (Year)': 2023,
      'Period (Quarter)': 'Q3',
      'Sales Force Name': 'Cardio - Renal Consultants',
      'Type of Sales Force': 'Traditional',
      'Number of Sales Representatives': 305,
      'Number of District Managers': 61,
      'Number of Regional Managers': 8,
      'US Brand Name\n(Product Promoted)': 'Kerendia',
      'Country Specific Brand Name\n(Product Promoted)': 'N/A',
      'Generic Name': 'finerenone',
      'Therapeutic Category': 'Nephrology and Transplantation',
      'Product Promotion Priority Order': 1,
      'Number of Full Time Equivalents (FTEs)': 305,
      'Primary Care Full Time Equivalents (FTEs)': 214,
      'Specialty Full Time Equivalents (FTEs)': 91,
      'Physicians Focus \n(Primary Care Physicians/ Specialty Physicians) ':
        'Primary Care and Specialty',
      'Specialty Physicians Targeted':
        'Primary Care, Endocrinology, Nephrology, Cardiology',
      'Co-Promotion (Yes/No)': 'No',
      'If YES \n(Name of a Partner Company)': 'N/A',
      'Contract Sales Force (Yes/No)': 'No',
      'If YES \n(Name of a CSO - Contract Sales Organization)': 'N/A',
      'Salary (Low)': 125000,
      'Salary (High)': 150000,
      'Target Bonus': 35000,
      'Reach \n': 130,
      'Frequency \n': 480,
      'Sales Force Notes': 'N/A',
    },
    {
      Country: 'United States',
      Company: 'Bayer',
      'Period (Year)': 2023,
      'Period (Quarter)': 'Q3',
      'Sales Force Name': 'Cardio - Renal Hybrid Specialists',
      'Type of Sales Force': 'Traditional',
      'Number of Sales Representatives': 40,
      'Number of District Managers': 61,
      'Number of Regional Managers': 8,
      'US Brand Name\n(Product Promoted)': 'Kerendia',
      'Country Specific Brand Name\n(Product Promoted)': 'N/A',
      'Generic Name': 'finerenone',
      'Therapeutic Category': 'Nephrology and Transplantation',
      'Product Promotion Priority Order': 1,
      'Number of Full Time Equivalents (FTEs)': 40,
      'Primary Care Full Time Equivalents (FTEs)': 15,
      'Specialty Full Time Equivalents (FTEs)': 25,
      'Physicians Focus \n(Primary Care Physicians/ Specialty Physicians) ':
        'Primary Care and Specialty',
      'Specialty Physicians Targeted':
        'Primary Care, Endocrinology, Nephrology, Cardiology',
      'Co-Promotion (Yes/No)': 'No',
      'If YES \n(Name of a Partner Company)': 'N/A',
      'Contract Sales Force (Yes/No)': 'No',
      'If YES \n(Name of a CSO - Contract Sales Organization)': 'N/A',
      'Salary (Low)': 135000,
      'Salary (High)': 155000,
      'Target Bonus': 40000,
      'Reach \n': 120,
      'Frequency \n': 480,
      'Sales Force Notes':
        'Renal-Hybrid Specialists are geography based, they mostly visit rural places where there is a need and where specialists do not go. Renal-Hybrid specialists visit everyone; primary care physicians, endocrinologists, cardiologists and nephrologists.',
    },
    {
      Country: 'United States',
      Company: 'Bayer',
      'Period (Year)': 2023,
      'Period (Quarter)': 'Q3',
      'Sales Force Name': 'Cardio - Renal Specialists',
      'Type of Sales Force': 'Traditional',
      'Number of Sales Representatives': 158,
      'Number of District Managers': 61,
      'Number of Regional Managers': 8,
      'US Brand Name\n(Product Promoted)': 'Kerendia',
      'Country Specific Brand Name\n(Product Promoted)': 'N/A',
      'Generic Name': 'finerenone',
      'Therapeutic Category': 'Nephrology and Transplantation',
      'Product Promotion Priority Order': 1,
      'Number of Full Time Equivalents (FTEs)': 158,
      'Primary Care Full Time Equivalents (FTEs)': 0,
      'Specialty Full Time Equivalents (FTEs)': 158,
      'Physicians Focus \n(Primary Care Physicians/ Specialty Physicians) ':
        'Specialty',
      'Specialty Physicians Targeted': ' Endocrinology, Nephrology, Cardiology',
      'Co-Promotion (Yes/No)': 'No',
      'If YES \n(Name of a Partner Company)': 'N/A',
      'Contract Sales Force (Yes/No)': 'No',
      'If YES \n(Name of a CSO - Contract Sales Organization)': 'N/A',
      'Salary (Low)': 125000,
      'Salary (High)': 150000,
      'Target Bonus': 35000,
      'Reach \n': 130,
      'Frequency \n': 480,
      'Sales Force Notes': 'N/A',
    },
    {
      Country: 'United States',
      Company: 'Bayer',
      'Period (Year)': 2023,
      'Period (Quarter)': 'Q3',
      'Sales Force Name': 'Hematology',
      'Type of Sales Force': 'Traditional',
      'Number of Sales Representatives': 10,
      'Number of District Managers': 3,
      'Number of Regional Managers': 1,
      'US Brand Name\n(Product Promoted)': 'Jivi',
      'Country Specific Brand Name\n(Product Promoted)': 'N/A',
      'Generic Name': 'Antihemophilic Factor (Recombinant), PEGylated-aucl',
      'Therapeutic Category': 'Oncology and Hematology',
      'Product Promotion Priority Order': 1,
      'Number of Full Time Equivalents (FTEs)': 10,
      'Primary Care Full Time Equivalents (FTEs)': 0,
      'Specialty Full Time Equivalents (FTEs)': 10,
      'Physicians Focus \n(Primary Care Physicians/ Specialty Physicians) ':
        'Specialty',
      'Specialty Physicians Targeted': 'Oncologists',
      'Co-Promotion (Yes/No)': 'No',
      'If YES \n(Name of a Partner Company)': 'N/A',
      'Contract Sales Force (Yes/No)': 'No',
      'If YES \n(Name of a CSO - Contract Sales Organization)': 'N/A',
      'Salary (Low)': 140000,
      'Salary (High)': 170000,
      'Target Bonus': 50000,
      'Reach \n': 20,
      'Frequency \n': 'N/A',
      'Sales Force Notes':
        'Bayer targets 125 Hemophilia Treatment Center accross the nation. Depending on the territory, representative can have from four to eight HTCs in their territoy. On average, they call on 1-2 physicians and other additional staff at each HTC. ',
    },
    {
      Country: 'United States',
      Company: 'Bayer',
      'Period (Year)': 2023,
      'Period (Quarter)': 'Q3',
      'Sales Force Name': 'Hematology',
      'Type of Sales Force': 'Traditional',
      'Number of Sales Representatives': 10,
      'Number of District Managers': 3,
      'Number of Regional Managers': 1,
      'US Brand Name\n(Product Promoted)': 'Kovaltry',
      'Country Specific Brand Name\n(Product Promoted)': 'N/A',
      'Generic Name': 'Antihemophilic Factor (Recombinant)',
      'Therapeutic Category': 'Oncology and Hematology',
      'Product Promotion Priority Order': 2,
      'Number of Full Time Equivalents (FTEs)': 0,
      'Primary Care Full Time Equivalents (FTEs)': 0,
      'Specialty Full Time Equivalents (FTEs)': 0,
      'Physicians Focus \n(Primary Care Physicians/ Specialty Physicians) ':
        'N/A',
      'Specialty Physicians Targeted': 'Oncologists',
      'Co-Promotion (Yes/No)': 'No',
      'If YES \n(Name of a Partner Company)': 'N/A',
      'Contract Sales Force (Yes/No)': 'No',
      'If YES \n(Name of a CSO - Contract Sales Organization)': 'N/A',
      'Salary (Low)': 140000,
      'Salary (High)': 170000,
      'Target Bonus': 50000,
      'Reach \n': 20,
      'Frequency \n': 'N/A',
      'Sales Force Notes': 'N/A',
    },
    {
      Country: 'United States',
      Company: 'Bayer',
      'Period (Year)': 2023,
      'Period (Quarter)': 'Q3',
      'Sales Force Name':
        'Oncology Specialty Sales Consultant, \nPrecision Medicines',
      'Type of Sales Force': 'Traditional',
      'Number of Sales Representatives': 16,
      'Number of District Managers': 2,
      'Number of Regional Managers': 1,
      'US Brand Name\n(Product Promoted)': 'Vitrakvi',
      'Country Specific Brand Name\n(Product Promoted)': 'N/A',
      'Generic Name': 'larotrectinib',
      'Therapeutic Category': 'Oncology and Hematology',
      'Product Promotion Priority Order': 1,
      'Number of Full Time Equivalents (FTEs)': 16,
      'Primary Care Full Time Equivalents (FTEs)': 0,
      'Specialty Full Time Equivalents (FTEs)': 16,
      'Physicians Focus \n(Primary Care Physicians/ Specialty Physicians) ':
        'Specialty',
      'Specialty Physicians Targeted': 'Oncologists',
      'Co-Promotion (Yes/No)': 'Yes',
      'If YES \n(Name of a Partner Company)': 'Loxo Oncology',
      'Contract Sales Force (Yes/No)': 'No',
      'If YES \n(Name of a CSO - Contract Sales Organization)': 'N/A',
      'Salary (Low)': 160000,
      'Salary (High)': 180000,
      'Target Bonus': 50000,
      'Reach \n': 100,
      'Frequency \n': 240,
      'Sales Force Notes': 'N/A',
    },
    {
      Country: 'United States',
      Company: 'Bayer',
      'Period (Year)': 2023,
      'Period (Quarter)': 'Q3',
      'Sales Force Name':
        'Oncology Specialty Sales Consultant, \nProstate Franchise',
      'Type of Sales Force': 'Traditional',
      'Number of Sales Representatives': 120,
      'Number of District Managers': 13,
      'Number of Regional Managers': 3,
      'US Brand Name\n(Product Promoted)': 'Nubeqa',
      'Country Specific Brand Name\n(Product Promoted)': 'N/A',
      'Generic Name': 'darolutamide',
      'Therapeutic Category': 'Oncology and Hematology',
      'Product Promotion Priority Order': 1,
      'Number of Full Time Equivalents (FTEs)': 100,
      'Primary Care Full Time Equivalents (FTEs)': 0,
      'Specialty Full Time Equivalents (FTEs)': 100,
      'Physicians Focus \n(Primary Care Physicians/ Specialty Physicians) ':
        'Specialty',
      'Specialty Physicians Targeted': 'Oncologists',
      'Co-Promotion (Yes/No)': 'No',
      'If YES \n(Name of a Partner Company)': 'N/A',
      'Contract Sales Force (Yes/No)': 'No',
      'If YES \n(Name of a CSO - Contract Sales Organization)': 'N/A',
      'Salary (Low)': 160000,
      'Salary (High)': 200000,
      'Target Bonus': 50000,
      'Reach \n': 85,
      'Frequency \n': 240,
      'Sales Force Notes': 'N/A',
    },
    {
      Country: 'United States',
      Company: 'Bayer',
      'Period (Year)': 2023,
      'Period (Quarter)': 'Q3',
      'Sales Force Name':
        'Oncology Specialty Sales Consultant, \nProstate Franchise',
      'Type of Sales Force': 'Traditional',
      'Number of Sales Representatives': 120,
      'Number of District Managers': 13,
      'Number of Regional Managers': 3,
      'US Brand Name\n(Product Promoted)': 'Xofigo',
      'Country Specific Brand Name\n(Product Promoted)': 'N/A',
      'Generic Name': 'radium-223 dichloride',
      'Therapeutic Category': 'Oncology and Hematology',
      'Product Promotion Priority Order': 2,
      'Number of Full Time Equivalents (FTEs)': 20,
      'Primary Care Full Time Equivalents (FTEs)': 0,
      'Specialty Full Time Equivalents (FTEs)': 20,
      'Physicians Focus \n(Primary Care Physicians/ Specialty Physicians) ':
        'Specialty',
      'Specialty Physicians Targeted': 'Oncologists',
      'Co-Promotion (Yes/No)': 'No',
      'If YES \n(Name of a Partner Company)': 'N/A',
      'Contract Sales Force (Yes/No)': 'No',
      'If YES \n(Name of a CSO - Contract Sales Organization)': 'N/A',
      'Salary (Low)': 160000,
      'Salary (High)': 200000,
      'Target Bonus': 50000,
      'Reach \n': 85,
      'Frequency \n': 240,
      'Sales Force Notes': 'N/A',
    },
    {
      Country: 'United States',
      Company: 'Bayer',
      'Period (Year)': 2023,
      'Period (Quarter)': 'Q3',
      'Sales Force Name':
        'Oncology - Prostate Franchise - Radiation Therapy Specialists',
      'Type of Sales Force': 'Traditional',
      'Number of Sales Representatives': 12,
      'Number of District Managers': 2,
      'Number of Regional Managers': 1,
      'US Brand Name\n(Product Promoted)': 'Xofigo',
      'Country Specific Brand Name\n(Product Promoted)': 'N/A',
      'Generic Name': 'radium-223 dichloride',
      'Therapeutic Category': 'Oncology and Hematology',
      'Product Promotion Priority Order': 1,
      'Number of Full Time Equivalents (FTEs)': 12,
      'Primary Care Full Time Equivalents (FTEs)': 0,
      'Specialty Full Time Equivalents (FTEs)': 12,
      'Physicians Focus \n(Primary Care Physicians/ Specialty Physicians) ':
        'Specialty',
      'Specialty Physicians Targeted': 'Oncologists',
      'Co-Promotion (Yes/No)': 'No',
      'If YES \n(Name of a Partner Company)': 'N/A',
      'Contract Sales Force (Yes/No)': 'No',
      'If YES \n(Name of a CSO - Contract Sales Organization)': 'N/A',
      'Salary (Low)': 160000,
      'Salary (High)': 180000,
      'Target Bonus': 50000,
      'Reach \n': 50,
      'Frequency \n': 300,
      'Sales Force Notes': 'N/A',
    },
    {
      Country: 'United States',
      Company: 'Bayer',
      'Period (Year)': 2023,
      'Period (Quarter)': 'Q3',
      'Sales Force Name':
        'Oncology Specialty Sales Consultant,\nTargeted Medicines',
      'Type of Sales Force': 'Traditional',
      'Number of Sales Representatives': 72,
      'Number of District Managers': 7,
      'Number of Regional Managers': 1,
      'US Brand Name\n(Product Promoted)': 'Stivarga',
      'Country Specific Brand Name\n(Product Promoted)': 'N/A',
      'Generic Name': 'regorafenib',
      'Therapeutic Category': 'Oncology and Hematology',
      'Product Promotion Priority Order': 1,
      'Number of Full Time Equivalents (FTEs)': 50,
      'Primary Care Full Time Equivalents (FTEs)': 0,
      'Specialty Full Time Equivalents (FTEs)': 50,
      'Physicians Focus \n(Primary Care Physicians/ Specialty Physicians) ':
        'Specialty',
      'Specialty Physicians Targeted': 'Oncologists',
      'Co-Promotion (Yes/No)': 'No',
      'If YES \n(Name of a Partner Company)': 'N/A',
      'Contract Sales Force (Yes/No)': 'No',
      'If YES \n(Name of a CSO - Contract Sales Organization)': 'N/A',
      'Salary (Low)': 150000,
      'Salary (High)': 200000,
      'Target Bonus': 50000,
      'Reach \n': 90,
      'Frequency \n': 240,
      'Sales Force Notes':
        'Between 6 and 8 reps are promoting Stivarga and Viktravi in 50:50 ratio, which is excluded from the ratio calculated in the FTE.',
    },
    {
      Country: 'United States',
      Company: 'Bayer',
      'Period (Year)': 2023,
      'Period (Quarter)': 'Q3',
      'Sales Force Name':
        'Oncology Specialty Sales Consultant,\nTargeted Medicines',
      'Type of Sales Force': 'Traditional',
      'Number of Sales Representatives': 72,
      'Number of District Managers': 7,
      'Number of Regional Managers': 1,
      'US Brand Name\n(Product Promoted)': 'Vitrakvi',
      'Country Specific Brand Name\n(Product Promoted)': 'N/A',
      'Generic Name': 'larotrectinib',
      'Therapeutic Category': 'Oncology and Hematology',
      'Product Promotion Priority Order': 2,
      'Number of Full Time Equivalents (FTEs)': 22,
      'Primary Care Full Time Equivalents (FTEs)': 0,
      'Specialty Full Time Equivalents (FTEs)': 22,
      'Physicians Focus \n(Primary Care Physicians/ Specialty Physicians) ':
        'Specialty',
      'Specialty Physicians Targeted': 'Oncologists',
      'Co-Promotion (Yes/No)': 'No',
      'If YES \n(Name of a Partner Company)': 'N/A',
      'Contract Sales Force (Yes/No)': 'No',
      'If YES \n(Name of a CSO - Contract Sales Organization)': 'N/A',
      'Salary (Low)': 150000,
      'Salary (High)': 200000,
      'Target Bonus': 50000,
      'Reach \n': 90,
      'Frequency \n': 240,
      'Sales Force Notes':
        'Between 6 and 8 reps are promoting Stivarga and Viktravi in 50:50 ratio, which is excluded from the ratio calculated in the FTE.',
    },
    {
      Country: 'United States',
      Company: 'Bayer',
      'Period (Year)': 2023,
      'Period (Quarter)': 'Q3',
      'Sales Force Name': "Women's Healthcare",
      'Type of Sales Force': 'Traditional',
      'Number of Sales Representatives': 121,
      'Number of District Managers': 16,
      'Number of Regional Managers': 3,
      'US Brand Name\n(Product Promoted)': 'Kyleena',
      'Country Specific Brand Name\n(Product Promoted)': 'N/A',
      'Generic Name': 'levonorgestrel',
      'Therapeutic Category': "Gynecology/Women's Health",
      'Product Promotion Priority Order': 1,
      'Number of Full Time Equivalents (FTEs)': 41,
      'Primary Care Full Time Equivalents (FTEs)': 3,
      'Specialty Full Time Equivalents (FTEs)': 38,
      'Physicians Focus \n(Primary Care Physicians/ Specialty Physicians) ':
        'Primary Care and Specialty',
      'Specialty Physicians Targeted':
        'Primary Care Physicians,\nGynecologists',
      'Co-Promotion (Yes/No)': 'No',
      'If YES \n(Name of a Partner Company)': 'N/A',
      'Contract Sales Force (Yes/No)': 'No',
      'If YES \n(Name of a CSO - Contract Sales Organization)': 'N/A',
      'Salary (Low)': 85000,
      'Salary (High)': 130000,
      'Target Bonus': 38000,
      'Reach \n': 100,
      'Frequency \n': 86,
      'Sales Force Notes': 'N/A',
    },
    {
      Country: 'United States',
      Company: 'Bayer',
      'Period (Year)': 2023,
      'Period (Quarter)': 'Q3',
      'Sales Force Name': "Women's Healthcare",
      'Type of Sales Force': 'Traditional',
      'Number of Sales Representatives': 121,
      'Number of District Managers': 16,
      'Number of Regional Managers': 3,
      'US Brand Name\n(Product Promoted)': 'Mirena',
      'Country Specific Brand Name\n(Product Promoted)': 'N/A',
      'Generic Name': 'levonorgestrel',
      'Therapeutic Category': "Gynecology/Women's Health",
      'Product Promotion Priority Order': 1,
      'Number of Full Time Equivalents (FTEs)': 40,
      'Primary Care Full Time Equivalents (FTEs)': 2,
      'Specialty Full Time Equivalents (FTEs)': 38,
      'Physicians Focus \n(Primary Care Physicians/ Specialty Physicians) ':
        'Primary Care and Specialty',
      'Specialty Physicians Targeted':
        'Primary Care Physicians,\nGynecologists',
      'Co-Promotion (Yes/No)': 'No',
      'If YES \n(Name of a Partner Company)': 'N/A',
      'Contract Sales Force (Yes/No)': 'No',
      'If YES \n(Name of a CSO - Contract Sales Organization)': 'N/A',
      'Salary (Low)': 85000,
      'Salary (High)': 130000,
      'Target Bonus': 38000,
      'Reach \n': 100,
      'Frequency \n': 86,
      'Sales Force Notes': 'N/A',
    },
    {
      Country: 'United States',
      Company: 'Bayer',
      'Period (Year)': 2023,
      'Period (Quarter)': 'Q3',
      'Sales Force Name': "Women's Healthcare",
      'Type of Sales Force': 'Traditional',
      'Number of Sales Representatives': 121,
      'Number of District Managers': 16,
      'Number of Regional Managers': 3,
      'US Brand Name\n(Product Promoted)': 'Skyla',
      'Country Specific Brand Name\n(Product Promoted)': 'N/A',
      'Generic Name': 'levonorgestrel',
      'Therapeutic Category': "Gynecology/Women's Health",
      'Product Promotion Priority Order': 1,
      'Number of Full Time Equivalents (FTEs)': 40,
      'Primary Care Full Time Equivalents (FTEs)': 2,
      'Specialty Full Time Equivalents (FTEs)': 38,
      'Physicians Focus \n(Primary Care Physicians/ Specialty Physicians) ':
        'Primary Care and Specialty',
      'Specialty Physicians Targeted':
        'Primary Care Physicians,\nGynecologists',
      'Co-Promotion (Yes/No)': 'No',
      'If YES \n(Name of a Partner Company)': 'N/A',
      'Contract Sales Force (Yes/No)': 'No',
      'If YES \n(Name of a CSO - Contract Sales Organization)': 'N/A',
      'Salary (Low)': 85000,
      'Salary (High)': 130000,
      'Target Bonus': 38000,
      'Reach \n': 100,
      'Frequency \n': 86,
      'Sales Force Notes': 'N/A',
    },
    {
      Country: 'United States',
      Company: 'Bayer',
      'Period (Year)': 2023,
      'Period (Quarter)': 'Q3',
      'Sales Force Name': 'Regional Account Leads - WHC',
      'Type of Sales Force': 'Institutional',
      'Number of Sales Representatives': 16,
      'Number of District Managers': 0,
      'Number of Regional Managers': 1,
      'US Brand Name\n(Product Promoted)': 'Kyleena',
      'Country Specific Brand Name\n(Product Promoted)': 'N/A',
      'Generic Name': 'levonorgestrel',
      'Therapeutic Category': "Gynecology/Women's Health",
      'Product Promotion Priority Order': 1,
      'Number of Full Time Equivalents (FTEs)': 5.5,
      'Primary Care Full Time Equivalents (FTEs)': 'N/A',
      'Specialty Full Time Equivalents (FTEs)': 5.5,
      'Physicians Focus \n(Primary Care Physicians/ Specialty Physicians) ':
        'Specialty',
      'Specialty Physicians Targeted': 'Gynecologists',
      'Co-Promotion (Yes/No)': 'No',
      'If YES \n(Name of a Partner Company)': 'N/A',
      'Contract Sales Force (Yes/No)': 'No',
      'If YES \n(Name of a CSO - Contract Sales Organization)': 'N/A',
      'Salary (Low)': 100000,
      'Salary (High)': 145000,
      'Target Bonus': 50000,
      'Reach \n': 'N/A',
      'Frequency \n': 'N/A',
      'Sales Force Notes': 'N/A',
    },
    {
      Country: 'United States',
      Company: 'Bayer',
      'Period (Year)': 2023,
      'Period (Quarter)': 'Q3',
      'Sales Force Name': 'Regional Account Leads - WHC',
      'Type of Sales Force': 'Institutional',
      'Number of Sales Representatives': 16,
      'Number of District Managers': 0,
      'Number of Regional Managers': 1,
      'US Brand Name\n(Product Promoted)': 'Mirena',
      'Country Specific Brand Name\n(Product Promoted)': 'N/A',
      'Generic Name': 'levonorgestrel',
      'Therapeutic Category': "Gynecology/Women's Health",
      'Product Promotion Priority Order': 1,
      'Number of Full Time Equivalents (FTEs)': 5.5,
      'Primary Care Full Time Equivalents (FTEs)': 'N/A',
      'Specialty Full Time Equivalents (FTEs)': 5.5,
      'Physicians Focus \n(Primary Care Physicians/ Specialty Physicians) ':
        'Specialty',
      'Specialty Physicians Targeted': 'Gynecologists',
      'Co-Promotion (Yes/No)': 'No',
      'If YES \n(Name of a Partner Company)': 'N/A',
      'Contract Sales Force (Yes/No)': 'No',
      'If YES \n(Name of a CSO - Contract Sales Organization)': 'N/A',
      'Salary (Low)': 100000,
      'Salary (High)': 145000,
      'Target Bonus': 50000,
      'Reach \n': 'N/A',
      'Frequency \n': 'N/A',
      'Sales Force Notes': 'N/A',
    },
    {
      Country: 'United States',
      Company: 'Bayer',
      'Period (Year)': 2023,
      'Period (Quarter)': 'Q3',
      'Sales Force Name': 'Regional Account Leads - WHC',
      'Type of Sales Force': 'Institutional',
      'Number of Sales Representatives': 16,
      'Number of District Managers': 0,
      'Number of Regional Managers': 1,
      'US Brand Name\n(Product Promoted)': 'Skyla',
      'Country Specific Brand Name\n(Product Promoted)': 'N/A',
      'Generic Name': 'levonorgestrel',
      'Therapeutic Category': "Gynecology/Women's Health",
      'Product Promotion Priority Order': 2,
      'Number of Full Time Equivalents (FTEs)': 5,
      'Primary Care Full Time Equivalents (FTEs)': 'N/A',
      'Specialty Full Time Equivalents (FTEs)': 5,
      'Physicians Focus \n(Primary Care Physicians/ Specialty Physicians) ':
        'Specialty',
      'Specialty Physicians Targeted': 'Gynecologists',
      'Co-Promotion (Yes/No)': 'No',
      'If YES \n(Name of a Partner Company)': 'N/A',
      'Contract Sales Force (Yes/No)': 'No',
      'If YES \n(Name of a CSO - Contract Sales Organization)': 'N/A',
      'Salary (Low)': 100000,
      'Salary (High)': 145000,
      'Target Bonus': 50000,
      'Reach \n': 'N/A',
      'Frequency \n': 'N/A',
      'Sales Force Notes': 'N/A',
    },
    {
      Country: 'United States',
      Company: 'Bayer',
      'Period (Year)': 2023,
      'Period (Quarter)': 'Q3',
      'Sales Force Name': 'Oncology Diagnostic Account Managers',
      'Type of Sales Force': 'Institutional',
      'Number of Sales Representatives': 5,
      'Number of District Managers': 1,
      'Number of Regional Managers': 1,
      'US Brand Name\n(Product Promoted)': 'TempusxT',
      'Country Specific Brand Name\n(Product Promoted)': 'N/A',
      'Generic Name': 'test kit',
      'Therapeutic Category': 'Oncology and Hematology',
      'Product Promotion Priority Order': 1,
      'Number of Full Time Equivalents (FTEs)': 2,
      'Primary Care Full Time Equivalents (FTEs)': 'N/A',
      'Specialty Full Time Equivalents (FTEs)': 2,
      'Physicians Focus \n(Primary Care Physicians/ Specialty Physicians) ':
        'Specialty',
      'Specialty Physicians Targeted': 'Oncologists',
      'Co-Promotion (Yes/No)': 'No',
      'If YES \n(Name of a Partner Company)': 'N/A',
      'Contract Sales Force (Yes/No)': 'No',
      'If YES \n(Name of a CSO - Contract Sales Organization)': 'N/A',
      'Salary (Low)': 160000,
      'Salary (High)': 175000,
      'Target Bonus': 40000,
      'Reach \n': 'N/A',
      'Frequency \n': 'N/A',
      'Sales Force Notes': 'N/A',
    },
    {
      Country: 'United States',
      Company: 'Bayer',
      'Period (Year)': 2023,
      'Period (Quarter)': 'Q3',
      'Sales Force Name': 'Oncology Diagnostic Account Managers',
      'Type of Sales Force': 'Institutional',
      'Number of Sales Representatives': 5,
      'Number of District Managers': 1,
      'Number of Regional Managers': 1,
      'US Brand Name\n(Product Promoted)': 'Afirma Xpression Atlas',
      'Country Specific Brand Name\n(Product Promoted)': 'N/A',
      'Generic Name': 'test kit',
      'Therapeutic Category': 'Oncology and Hematology',
      'Product Promotion Priority Order': 2,
      'Number of Full Time Equivalents (FTEs)': 1.5,
      'Primary Care Full Time Equivalents (FTEs)': 'N/A',
      'Specialty Full Time Equivalents (FTEs)': 1.5,
      'Physicians Focus \n(Primary Care Physicians/ Specialty Physicians) ':
        'Specialty',
      'Specialty Physicians Targeted': 'Oncologists',
      'Co-Promotion (Yes/No)': 'No',
      'If YES \n(Name of a Partner Company)': 'N/A',
      'Contract Sales Force (Yes/No)': 'No',
      'If YES \n(Name of a CSO - Contract Sales Organization)': 'N/A',
      'Salary (Low)': 160000,
      'Salary (High)': 175000,
      'Target Bonus': 40000,
      'Reach \n': 'N/A',
      'Frequency \n': 'N/A',
      'Sales Force Notes': 'N/A',
    },
    {
      Country: 'United States',
      Company: 'Bayer',
      'Period (Year)': 2023,
      'Period (Quarter)': 'Q3',
      'Sales Force Name': 'Oncology Diagnostic Account Managers',
      'Type of Sales Force': 'Institutional',
      'Number of Sales Representatives': 5,
      'Number of District Managers': 1,
      'Number of Regional Managers': 1,
      'US Brand Name\n(Product Promoted)': 'Test4TRK',
      'Country Specific Brand Name\n(Product Promoted)': 'N/A',
      'Generic Name': 'test kit',
      'Therapeutic Category': 'Oncology and Hematology',
      'Product Promotion Priority Order': 2,
      'Number of Full Time Equivalents (FTEs)': 1.5,
      'Primary Care Full Time Equivalents (FTEs)': 'N/A',
      'Specialty Full Time Equivalents (FTEs)': 1.5,
      'Physicians Focus \n(Primary Care Physicians/ Specialty Physicians) ':
        'Specialty',
      'Specialty Physicians Targeted': 'Oncologists',
      'Co-Promotion (Yes/No)': 'No',
      'If YES \n(Name of a Partner Company)': 'N/A',
      'Contract Sales Force (Yes/No)': 'No',
      'If YES \n(Name of a CSO - Contract Sales Organization)': 'N/A',
      'Salary (Low)': 160000,
      'Salary (High)': 175000,
      'Target Bonus': 40000,
      'Reach \n': 'N/A',
      'Frequency \n': 'N/A',
      'Sales Force Notes': 'N/A',
    },
    {
      Country: 'United States',
      Company: 'Bayer',
      'Period (Year)': 2023,
      'Period (Quarter)': 'Q3',
      'Sales Force Name': 'Oncology Key Account Executives',
      'Type of Sales Force': 'Institutional',
      'Number of Sales Representatives': 12,
      'Number of District Managers': 0,
      'Number of Regional Managers': 1,
      'US Brand Name\n(Product Promoted)': 'Nubeqa',
      'Country Specific Brand Name\n(Product Promoted)': 'N/A',
      'Generic Name': 'darolutamide',
      'Therapeutic Category': 'Oncology and Hematology',
      'Product Promotion Priority Order': 1,
      'Number of Full Time Equivalents (FTEs)': 4,
      'Primary Care Full Time Equivalents (FTEs)': 'N/A',
      'Specialty Full Time Equivalents (FTEs)': 4,
      'Physicians Focus \n(Primary Care Physicians/ Specialty Physicians) ':
        'Specialty',
      'Specialty Physicians Targeted': 'Oncologists',
      'Co-Promotion (Yes/No)': 'No',
      'If YES \n(Name of a Partner Company)': 'N/A',
      'Contract Sales Force (Yes/No)': 'No',
      'If YES \n(Name of a CSO - Contract Sales Organization)': 'N/A',
      'Salary (Low)': 175000,
      'Salary (High)': 200000,
      'Target Bonus': 50000,
      'Reach \n': 'N/A',
      'Frequency \n': 'N/A',
      'Sales Force Notes': 'N/A',
    },
    {
      Country: 'United States',
      Company: 'Bayer',
      'Period (Year)': 2023,
      'Period (Quarter)': 'Q3',
      'Sales Force Name': 'Oncology Key Account Executives',
      'Type of Sales Force': 'Institutional',
      'Number of Sales Representatives': 12,
      'Number of District Managers': 0,
      'Number of Regional Managers': 1,
      'US Brand Name\n(Product Promoted)': 'Xofigo',
      'Country Specific Brand Name\n(Product Promoted)': 'N/A',
      'Generic Name': 'radium-223 dichloride',
      'Therapeutic Category': 'Oncology and Hematology',
      'Product Promotion Priority Order': 1,
      'Number of Full Time Equivalents (FTEs)': 4,
      'Primary Care Full Time Equivalents (FTEs)': 'N/A',
      'Specialty Full Time Equivalents (FTEs)': 4,
      'Physicians Focus \n(Primary Care Physicians/ Specialty Physicians) ':
        'Specialty',
      'Specialty Physicians Targeted': 'Oncologists',
      'Co-Promotion (Yes/No)': 'No',
      'If YES \n(Name of a Partner Company)': 'N/A',
      'Contract Sales Force (Yes/No)': 'No',
      'If YES \n(Name of a CSO - Contract Sales Organization)': 'N/A',
      'Salary (Low)': 175000,
      'Salary (High)': 200000,
      'Target Bonus': 50000,
      'Reach \n': 'N/A',
      'Frequency \n': 'N/A',
      'Sales Force Notes': 'N/A',
    },
  ];
  displayedColumns: string[] = [
    'Country',
    'Company',
    'Period (Year)',
    'Period (Quarter)',
    'Sales Force Name',
    'Type of Sales Force',
    'Number of Sales Representatives',
    'Number of District Managers',
    'Number of Regional Managers',
    'Generic Name',
  ];
  dataSource = new MatTableDataSource<any>(this.ELEMENT_DATA);

  @ViewChild(MatPaginator) paginator: MatPaginator | any;
  constructor() {}

  ngOnInit(): void {
    this.createDoubleBarChart();
  }

  createDoubleBarChart(): void {
    const ctx = document.getElementById('doubleBarChart') as HTMLCanvasElement;

    this.chart = new Chart(ctx, {
      type: 'bar',
      data: {
        labels: [
          'Anti-Infective',
          'CNS, Pain and Anesthesia',
          'Dermatology',
          'Oncology and Hematology',
        ],
        datasets: [
          {
            label: 'Primary Care',
            backgroundColor: '#397F7D',
            borderColor: '#D2EBEA',
            borderWidth: 1,
            borderRadius: 5,
            data: [200, 315, 150, 520],
          },
          {
            label: 'Speciality',
            backgroundColor: '#91439A',
            borderColor: '#EBD7ED',
            borderWidth: 1,
            borderRadius: 5,    
            data: [450, 563, 250, 420],
          },
        ],
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        scales: {
          x: {
            beginAtZero: true,
          },
          y: {
            beginAtZero: true,
          },
        },
      },
    });
    ctx.style.height = '400px'; // Set your desired height
  }

  ngAfterViewInit() {
    this.dataSource.paginator = this.paginator;
  }
}
